default: &default
  adapter: mysql2
  encoding: utf8
  pool:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: vtapp_development

test:
  <<: *default
  database: vtapp_test

production:
  <<: *default
  database: vtapp_production
  username:
  password: